### ISSUE TITLE
Backpress state loss

### ISSUE THREAD

**Issue by dogancankilic** [ericktijerou/photosearch#1]
After navigating back from the detail page I'm losing my current state.

**Comment by ericktijerou** [comment]
> 

Hi! @dogancankilic 👋 

Thanks a lot for your feedback I appreciate that.

I'm going to fix this issue during this weekend. 🚀

**Comment by dogancankilic** [comment]
Hi @ericktijerou,

[This](https://stackoverflow.com/a/67402471/10332258) solved the issue.
